#!/bin/bash
# Enable strict mode
set -e

echo "--- Module 3: Terminal Setup ---"

# --- Permission Fix ---
# Fixes 'permission denied: /home/$USER/.local/bin'
echo "[*] Verifying permissions for $HOME/.local/bin..."
mkdir -p "$HOME/.local/bin"
sudo chown -R "$USER":"$USER" "$HOME/.local/bin"
echo "[+] .local/bin permissions corrected."

# --- Zsh and Oh My Zsh ---
if [ "$SHELL" != "/bin/zsh" ]; then
    echo "[*] Changing default shell to Zsh..."
    ZSH_PATH=$(which zsh)
    if chsh -s "$ZSH_PATH"; then
        echo "[+] Shell changed to Zsh. Please log out and back in."
    else
        echo "[!] Could not change shell automatically. Run: chsh -s $(which zsh)"
    fi
else
    echo "[+] Default shell is already Zsh."
fi

if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "[*] Installing Oh My Zsh..."
    # --unattended makes it non-interactive and does not switch shell (we do it above)
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    echo "[+] Oh My Zsh installed."
else
    echo "[+] Oh My Zsh is already installed."
fi

# --- Zsh Plugins ---
ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}

if [ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]; then
    echo "[*] Installing zsh-autosuggestions..."
    git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
else
    echo "[+] zsh-autosuggestions is already installed."
fi

if [ ! -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]; then
    echo "[*] Installing zsh-syntax-highlighting..."
    git clone https://github.com/zsh-users/zsh-syntax-highlighting "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
else
    echo "[+] zsh-syntax-highlighting is already installed."
fi

# Activate plugins in .zshrc robustly.
# This approach reads the current plugin list, adds the new plugins if they are
# not already present, then rewrites the line — safe regardless of existing plugins.
echo "[*] Activating Zsh plugins in .zshrc..."
ZSHRC="$HOME/.zshrc"
PLUGINS_TO_ADD=("zsh-autosuggestions" "zsh-syntax-highlighting")

# Extract current plugin list (e.g. "git z docker")
# Use sed to strip the literal 'plugins=(' prefix and ')' suffix — NOT tr -d,
# which would delete individual characters and corrupt plugin names.
current_plugins=$(sed -n 's/^plugins=(\(.*\))/\1/p' "$ZSHRC" | head -1 | xargs)

updated_plugins="$current_plugins"
for plugin in "${PLUGINS_TO_ADD[@]}"; do
    if ! echo " $updated_plugins " | grep -q " $plugin "; then
        updated_plugins="$updated_plugins $plugin"
    fi
done
# Trim and write back
updated_plugins=$(echo "$updated_plugins" | xargs)
sed -i.bak "s/^plugins=(.*)/plugins=($updated_plugins)/" "$ZSHRC"
echo "[+] Zsh plugins activated: ($updated_plugins)"

# --- $PATH and Alias Configuration ---
echo "[*] Configuring \$PATH and aliases in .zshrc..."

# --- pipx ---
if ! grep -q 'eval "$(pipx ensurepath &>/dev/null)"' "$HOME/.zshrc"; then
    # Remove old, broken lines if they exist
    sed -i '/pipx ensurepath/d' "$HOME/.zshrc"
    echo 'eval "$(pipx ensurepath &>/dev/null)"' >> "$HOME/.zshrc"
    echo "[+] Added pipx ensurepath to .zshrc"
else
    echo "[+] pipx ensurepath is already in .zshrc."
fi

# --- .local/bin (lvim), Flatpak (auto), and Aliases (static) ---
# Use a marker to be idempotent
if ! grep -q "# --- End of \$PATH and Alias config ---" "$HOME/.zshrc"; then
    echo "-> Adding \$PATH and alias-loading block..."
    cat << 'EOF' >> ~/.zshrc

# --- $PATH Configuration ---
# (Block added by the universal-linux-setup script)

# Add local bin folder
if [ -d "$HOME/.local/bin" ] && [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    export PATH="$PATH:$HOME/.local/bin"
fi

# Add Flatpak bin folders
if [ -d "/var/lib/flatpak/exports/bin" ] && [[ ":$PATH:" != *":/var/lib/flatpak/exports/bin:"* ]]; then
    export PATH="$PATH:/var/lib/flatpak/exports/bin"
fi
if [ -d "$HOME/.local/share/flatpak/exports/bin" ] && [[ ":$PATH:" != *":$HOME/.local/share/flatpak/exports/bin:"* ]]; then
    export PATH="$PATH:$HOME/.local/share/flatpak/exports/bin"
fi

# --- Load Generated Flatpak Aliases ---
# Loads the alias file generated by 'update-flatpak-aliases.sh'
ALIAS_FILE_PATH="$HOME/.zshrc-flatpak-aliases"
if [ -f "$ALIAS_FILE_PATH" ]; then
    source "$ALIAS_FILE_PATH"
fi
# --- End of $PATH and Alias config ---
EOF
    echo "[+] \$PATH and Flatpak aliases configured in .zshrc"
else
    echo "[+] \$PATH and Alias block already exists in .zshrc. Skipping."
fi

echo "--- Module 3 Finished ---"