#!/bin/bash
# Enable strict mode
set -e

echo "--- Module 3: Terminal Setup ---"

# --- Permission Fix ---
# Fixes 'permission denied: /home/sam/.local/bin'
echo "[*] Verifying permissions for /home/$USER/.local/bin..."
mkdir -p "$HOME/.local/bin"
sudo chown -R $USER:$USER "$HOME/.local/bin"
echo "[+] .local/bin permissions corrected."

# --- Zsh and Oh My Zsh ---
if [ "$SHELL" != "/bin/zsh" ]; then
    echo "[*] Changing default shell to Zsh..."
    ZSH_PATH=$(which zsh)
    if chsh -s "$ZSH_PATH"; then
        echo "[+] Shell changed to Zsh. Please log out and back in."
    else
        echo "[!] Could not change shell."
    fi
else
    echo "[+] Default shell is already Zsh."
fi

if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "[*] Installing Oh My Zsh..."
    # --unattended makes it non-interactive
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    echo "[+] Oh My Zsh installed."
else
    echo "[+] Oh My Zsh is already installed."
fi

# --- Zsh Plugins ---
ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]; then
    echo "[*] Installing zsh-autosuggestions..."
    git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
else
    echo "[+] zsh-autosuggestions is already installed."
fi
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]; then
    echo "[*] Installing zsh-syntax-highlighting..."
    git clone https://github.com/zsh-users/zsh-syntax-highlighting "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
else
    echo "[+] zsh-syntax-highlighting is already installed."
fi
# Replace the 'plugins=(git)' line with the full list
sed -i.bak 's/^plugins=(git)$/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc
echo "[+] Zsh plugins activated in .zshrc"

# --- Neovim / LunarVim Environment ---
echo "[*] Installing LunarVim dependencies..."
if [ "$DISTRO" == "arch" ]; then
    sudo pacman -S --noconfirm --needed neovim nodejs npm
elif [ "$DISTRO" == "debian" ]; then
    sudo apt-get install -y neovim nodejs npm
fi

# Install LunarVim (this is idempotent)
if ! command -v lvim &> /dev/null; then
    echo "[*] Installing LunarVim (lvim)..."
    LV_BRANCH='release-1.4/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.4/neovim-0.9/utils/installer/install.sh)
    echo "[+] LunarVim installed."
else
    echo "[+] LunarVim (lvim) is already installed."
fi

# --- $PATH and Alias Configuration ---
echo "[*] Configuring $PATH and aliases in .zshrc..."

# --- pipx ---
# This section is now only relevant for Debian/Ubuntu, but
# the 'if ! grep' check makes it safe for Arch (it will just be skipped).
# The redirect '&>/dev/null' silences all output to fix eval errors.
if ! grep -q 'eval "$(pipx ensurepath &>/dev/null)"' "$HOME/.zshrc"; then
    # Remove old, broken lines if they exist
    sed -i '/pipx ensurepath/d' "$HOME/.zshrc"
    echo 'eval "$(pipx ensurepath &>/dev/null)"' >> "$HOME/.zshrc"
    echo "[+] Added pipx ensurepath to .zshrc"
else
    echo "[+] pipx ensurepath is already in .zshrc."
fi

# --- .local/bin (lvim), Flatpak (auto), and Aliases (static) ---
# Use a marker to be idempotent
if ! grep -q "# --- End of $PATH and Alias config ---" "$HOME/.zshrc"; then
    echo "-> Adding $PATH and alias-loading block..."
    cat << 'EOF' >> ~/.zshrc

# --- $PATH Configuration ---
# (Block added by the global-linux-desktop script)

# Add local bin folder (for lvim)
if [ -d "$HOME/.local/bin" ] && [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    export PATH="$PATH:$HOME/.local/bin"
fi

# Add Flatpak bin folders (System's automatic attempt)
if [ -d "/var/lib/flatpak/exports/bin" ] && [[ ":$PATH:" != *":/var/lib/flatpak/exports/bin:"* ]]; then
    export PATH="$PATH:/var/lib/flatpak/exports/bin"
fi
if [ -d "$HOME/.local/share/flatpak/exports/bin" ] && [[ ":$PATH:" != *":$HOME/.local/share/flatpak/exports/bin:"* ]]; then
    export PATH="$PATH:$HOME/.local/share/flatpak/exports/bin"
fi

# --- Load Generated Flatpak Aliases ---
# Loads the alias file generated by 'update-flatpak-aliases.sh'
ALIAS_FILE_PATH="$HOME/.zshrc-flatpak-aliases"
if [ -f "$ALIAS_FILE_PATH" ]; then
    source "$ALIAS_FILE_PATH"
fi
# --- End of $PATH and Alias config ---
EOF
    echo "[+] $PATH and Flatpak aliases configured in .zshrc"
else
    echo "[+] $PATH and Alias block already exists in .zshrc. Skipping."
fi
echo "--- Module 3 Finished ---"