#!/bin/bash
#
# MODULE: Flatpak Alias Updater
#
# This script generates a static file with aliases for all
# installed Flatpak applications.
# It is designed to be called by install.sh or manually (via 'update' alias).

set -e

# The file to be generated
ALIAS_FILE="$HOME/.zshrc-flatpak-aliases"

echo "--- Generating Flatpak aliases in $ALIAS_FILE ---"

# Write the header (>) overwrites the file each time
echo "# --- Flatpak Aliases (Generated by update-flatpak-aliases.sh) ---" > "$ALIAS_FILE"
echo "# This file is regenerated every time that script is run." >> "$ALIAS_FILE"
echo "" >> "$ALIAS_FILE"

# --- 'awk' Logic ---
# Fixes the 'alias studio' bug for apps with long names
# 1. Iterate through all fields (columns) of each line.
# 2. Find the field that contains a dot ('.') - that is the App ID.
# 3. Split that App ID by the dot and use the last part as the alias.
flatpak list --app | awk '{
    app_id = "";
    # Iterate through all fields to find the App ID
    for (i = 1; i <= NF; i++) {
        if ($i ~ /\./) {
            app_id = $i;
            break;
        }
    }
    
    if (app_id != "") {
        n = split(app_id, parts, ".");
        alias_name = tolower(parts[n]);
        # Print the alias to the file
        printf "alias %s=\047flatpak run %s\047\n", alias_name, app_id
    }
}' >> "$ALIAS_FILE" # (>>) Appends to the file

echo "[+] Flatpak aliases generated."